
package co.com.service.consumer;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-05-05T12:49:14.920-05:00
 * Generated source version: 2.4.2
 * 
 */
public final class IGreeting_GreetingImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://consumer.service.com.co/", "GreetingImplService");

    private IGreeting_GreetingImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GreetingImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GreetingImplService ss = new GreetingImplService(wsdlURL, SERVICE_NAME);
        IGreeting port = ss.getGreetingImplPort();  
        
        {
        System.out.println("Invoking greetingWithName...");
        java.lang.String _greetingWithName_arg0 = "_greetingWithName_arg01830122596";
        java.lang.String _greetingWithName__return = port.greetingWithName(_greetingWithName_arg0);
        System.out.println("greetingWithName.result=" + _greetingWithName__return);


        }

        System.exit(0);
    }

}
