package co.com.service.consumer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2018-05-05T12:49:15.011-05:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://consumer.service.com.co/", name = "IGreeting")
@XmlSeeAlso({ObjectFactory.class})
public interface IGreeting {

    @WebMethod(action = "urn:GreetingWithName")
    @RequestWrapper(localName = "greetingWithName", targetNamespace = "http://consumer.service.com.co/", className = "co.com.service.consumer.GreetingWithName")
    @ResponseWrapper(localName = "greetingWithNameResponse", targetNamespace = "http://consumer.service.com.co/", className = "co.com.service.consumer.GreetingWithNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String greetingWithName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
